export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function KursDuniaLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return <>{children}</>
}
